version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: your_strong_password_here
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
