# Generated by Django 5.2.4 on 2025-07-30 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Şube Adı")),
                ("adres", models.TextField(verbose_name="Adres")),
                ("telefon", models.CharField(max_length=20, verbose_name="Telefon")),
                ("yonetici", models.CharField(max_length=100, verbose_name="Yönetici")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Şube",
                "verbose_name_plural": "Şubeler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Personel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Ad")),
                ("soyad", models.CharField(max_length=100, verbose_name="Soyad")),
                ("pozisyon", models.CharField(max_length=100, verbose_name="Pozisyon")),
                (
                    "maas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Maaş",
                    ),
                ),
                (
                    "ise_baslama_tarihi",
                    models.DateField(verbose_name="İşe Başlama Tarihi"),
                ),
                ("telefon", models.CharField(max_length=20, verbose_name="Telefon")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "sube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yonetim.sube",
                        verbose_name="Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personel",
                "verbose_name_plural": "Personel",
                "ordering": ["ad", "soyad"],
            },
        ),
        migrations.CreateModel(
            name="GelirGider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[("gelir", "Gelir"), ("gider", "Gider")],
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                ("kategori", models.CharField(max_length=100, verbose_name="Kategori")),
                ("aciklama", models.TextField(verbose_name="Açıklama")),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Tutar",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "sube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yonetim.sube",
                        verbose_name="Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gelir/Gider",
                "verbose_name_plural": "Gelir/Giderler",
                "ordering": ["-tarih", "-olusturma_tarihi"],
            },
        ),
    ]
