# Generated by Django 5.2.4 on 2025-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sube",
            name="tur",
            field=models.CharField(
                choices=[("cafe", "Cafe"), ("otel", "Otel")],
                default="cafe",
                max_length=10,
                verbose_name="Şube Türü",
            ),
        ),
    ]
