# Generated by Django 5.2.4 on 2025-07-30 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0002_sube_tur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personel",
            name="maas",
        ),
        migrations.CreateModel(
            name="Mesai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "saat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Mesai Saati",
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "personel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yonetim.personel",
                        verbose_name="Personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesai",
                "verbose_name_plural": "Mesailer",
                "ordering": ["-tarih", "-olusturma_tarihi"],
            },
        ),
    ]
