# Generated by Django 5.2.4 on 2025-07-31 08:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mesai",
            name="saat",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Mesai Saati",
            ),
        ),
    ]
