# Generated by Django 5.2.4 on 2025-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0005_alter_mesai_saat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gelirgider",
            name="aciklama",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="gelirgider",
            name="kategori",
            field=models.CharField(
                choices=[("nakit", "NAKİT")],
                default="nakit",
                max_length=100,
                verbose_name="Kategori",
            ),
        ),
    ]
