# Generated by Django 5.2.4 on 2025-07-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0006_gelirgider_kategori_aciklama"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
