# Generated by Django 5.2.4 on 2025-07-31 15:00

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # --- İzinleri Kod Adlarına Göre Belirle ---
    # Muhasebe (Tüm Yetkiler)
    muhasebe_perms_codenames = [
        "add_sube",
        "change_sube",
        "delete_sube",
        "view_sube",
        "add_personel",
        "change_personel",
        "delete_personel",
        "view_personel",
        "add_mesai",
        "change_mesai",
        "delete_mesai",
        "view_mesai",
        "add_gelirgider",
        "change_gelirgider",
        "delete_gelirgider",
        "view_gelirgider",
    ]

    # Şube Müdürü (Personel + Mesai Yönetimi)
    sube_muduru_perms_codenames = [
        "add_personel",
        "change_personel",
        "delete_personel",
        "view_personel",
        "add_mesai",
        "change_mesai",
        "delete_mesai",
        "view_mesai",
    ]

    # Patron (Sadece Görme - Anasayfa ve Gelir/Gider)
    patron_perms_codenames = [
        "view_gelirgider",
    ]

    # --- Grupları Oluştur ve İzinleri Ata ---
    # Muhasebe Grubu
    muhasebe_group, created = Group.objects.get_or_create(name="Muhasebe")
    muhasebe_permissions = Permission.objects.filter(
        content_type__app_label="yonetim", codename__in=muhasebe_perms_codenames
    )
    muhasebe_group.permissions.set(muhasebe_permissions)

    # Şube Müdürü Grubu
    sube_muduru_group, created = Group.objects.get_or_create(name="Şube Müdürü")
    sube_muduru_permissions = Permission.objects.filter(
        content_type__app_label="yonetim", codename__in=sube_muduru_perms_codenames
    )
    sube_muduru_group.permissions.set(sube_muduru_permissions)

    # Patron Grubu
    patron_group, created = Group.objects.get_or_create(name="Patron")
    patron_permissions = Permission.objects.filter(
        content_type__app_label="yonetim", codename__in=patron_perms_codenames
    )
    patron_group.permissions.set(patron_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0007_delete_userprofile"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
