# Generated by Django 5.2.4 on 2025-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0008_create_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-posta"),
        ),
    ]
