# Generated by Django 5.2.4 on 2025-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0009_alter_personel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personel',
            options={'ordering': ['ad', 'soyad'], 'verbose_name': 'Personel', 'verbose_name_plural': 'Personeller'},
        ),
        migrations.AlterField(
            model_name='personel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
    ]
